name: Maven Package

on:
  push:
    branches:
      - '*'

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    - name: Set up JDK 17
      uses: actions/setup-java@v4
      with:
        java-version: '17'
        distribution: 'zulu'

    - name: Publish package
      run: ./mvnw deploy -DskipTests
      env:
        GITHUB_TOKEN: ${{ github.token }}
